server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - StripPrefix=0
      routes:
        - id: budget
          uri: lb://BUDGET-SERVICE
          predicates:
            - Path=/api/budgets/**

        - id: expense
          uri: lb://EXPENSE-SERVICE
          predicates:
            - Path=/api/expenses/**

        - id: notification
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**

        - id: user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
